server:
 port: 9020
 

spring:
 application:
  name: gateway-service
 cloud:
    gateway:
      routes:
        - id: api-revenda-service
          uri: http://api-revenda-service:8084/
          predicates: Path=/revenda/**
          filters:
            - RewritePath=/revenda(?<segment>/?.*), $\{segment}
            - RemoveRequestHeader=Cookie
        - id: api-mercadolivre-service
          uri: http://api-mercadolivre-service:8083/
          predicates:
            - Path=/mercadolivre/**
          filters:
            - RewritePath=/mercadolivre(?<segment>/?.*), $\{segment}
            - RemoveRequestHeader=Cookie
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allow-credentials: true
            max-age: 1800
        add-to-simple-url-handler-mapping: true
      default-filters: 
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
            
management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway
            
api:
  sendreport:
    uri: www.repor.com.br
  version: 2.0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG